import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { COULOMB_K } from "../lib/science/electrostatics/field.ts";
import {
  MACRO_DT_S,
  integrateFor,
  mechanicalEnergy,
  stepMacro,
} from "../lib/science/electrostatics/integrator.ts";
import { ELECTROSTATIC_PRESETS, initialRuntime, stepRuntime } from "../models/electrostatic.ts";

/**
 * Numerical regression of the production integrator (1/960 s velocity Verlet + bounded 1/2/4
 * substeps) against RK4 reference fixtures generated by the Owner-approved validation harness
 * (tests/fixtures/electrostatic/generate_reference.py). Gates (Numerical Envelope Validation §3.4):
 * event mismatch 0, max path error ≤ 0.025 mm, max normalized energy drift ≤ 0.1 %.
 */

const MAX_PATH_ERROR_M = 0.025e-3;
const MAX_ENERGY_DRIFT = 1e-3;
const DOMAIN = { xmin: -2, xmax: 2, ymin: -1.5, ymax: 1.5 };

async function loadFixture(name) {
  return JSON.parse(await readFile(new URL(`./fixtures/electrostatic/${name}`, import.meta.url), "utf8"));
}

function systemOf(fixtureCase) {
  return {
    sources: fixtureCase.sources.map((s, i) => ({ id: `s${i + 1}`, x_m: s.x_m, y_m: s.y_m, q_C: s.q_C })),
    domain: DOMAIN,
    rCore_m: fixtureCase.rCore_m,
  };
}

/** Test-only oracle: raw Coulomb acceleration, defined even on a core boundary. */
function rawAcceleration(x, y, fixtureCase) {
  let ax = 0;
  let ay = 0;
  const beta = fixtureCase.qTest_C / fixtureCase.mass_kg;
  for (const s of fixtureCase.sources) {
    const dx = x - s.x_m;
    const dy = y - s.y_m;
    const r2 = dx * dx + dy * dy;
    const scale = (beta * COULOMB_K * s.q_C) / (r2 * Math.sqrt(r2));
    ax += scale * dx;
    ay += scale * dy;
  }
  return [ax, ay];
}

/** Cubic Hermite position between two trace states (runs use h ≤ 1/960 s). */
function cubicPosition(a, b, t) {
  const h = b.t_s - a.t_s;
  if (h === 0) return [a.x_m, a.y_m];
  const s = (t - a.t_s) / h;
  const h00 = 2 * s ** 3 - 3 * s ** 2 + 1;
  const h10 = s ** 3 - 2 * s ** 2 + s;
  const h01 = -2 * s ** 3 + 3 * s ** 2;
  const h11 = s ** 3 - s ** 2;
  return [
    h00 * a.x_m + h10 * h * a.vx_mps + h01 * b.x_m + h11 * h * b.vx_mps,
    h00 * a.y_m + h10 * h * a.vy_mps + h01 * b.y_m + h11 * h * b.vy_mps,
  ];
}

/** Quintic Hermite position between two reference grid rows using position, velocity and acceleration. */
function quinticPosition(a, b, t, fixtureCase) {
  const h = b[0] - a[0];
  const s = (t - a[0]) / h;
  const [aax, aay] = rawAcceleration(a[1], a[2], fixtureCase);
  const [bax, bay] = rawAcceleration(b[1], b[2], fixtureCase);
  const s2 = s * s;
  const s3 = s2 * s;
  const s4 = s3 * s;
  const s5 = s4 * s;
  const H0 = 1 - 10 * s3 + 15 * s4 - 6 * s5;
  const H1 = s - 6 * s3 + 8 * s4 - 3 * s5;
  const H2 = 0.5 * (s2 - 3 * s3 + 3 * s4 - s5);
  const H3 = 0.5 * (s3 - 2 * s4 + s5);
  const H4 = -4 * s3 + 7 * s4 - 3 * s5;
  const H5 = 10 * s3 - 15 * s4 + 6 * s5;
  const axis = (p0, v0, a0, p1, v1, a1) =>
    H0 * p0 + H1 * h * v0 + H2 * h * h * a0 + H3 * h * h * a1 + H4 * h * v1 + H5 * p1;
  return [axis(a[1], a[3], aax, b[1], b[3], bax), axis(a[2], a[4], aay, b[2], b[4], bay)];
}

function traceAt(trace, t) {
  let lo = 0;
  let hi = trace.length - 1;
  if (t >= trace[hi].t_s) return [trace[hi].x_m, trace[hi].y_m];
  while (lo + 1 < hi) {
    const mid = (lo + hi) >> 1;
    if (trace[mid].t_s <= t) lo = mid;
    else hi = mid;
  }
  return cubicPosition(trace[lo], trace[hi], t);
}

function referenceAt(grid, t, fixtureCase) {
  if (t >= grid[grid.length - 1][0]) return [grid[grid.length - 1][1], grid[grid.length - 1][2]];
  const step = grid[1][0] - grid[0][0];
  const i = Math.min(grid.length - 2, Math.floor(t / step));
  return quinticPosition(grid[i], grid[i + 1], t, fixtureCase);
}

/** Run the production integrator on one fixture case and measure it against the RK4 reference. */
function evaluate(fixtureCase) {
  const initial = { x_m: fixtureCase.r0_m[0], y_m: fixtureCase.r0_m[1], vx_mps: fixtureCase.v0_mps[0], vy_mps: fixtureCase.v0_mps[1], t_s: 0 };
  const particle = { q_C: fixtureCase.qTest_C, mass_kg: fixtureCase.mass_kg };
  const system = systemOf(fixtureCase);
  const trace = [initial];
  const start = mechanicalEnergy(initial, particle, system);
  let maxDrift = 0;
  const run = integrateFor(initial, particle, system, fixtureCase.tEnd_s, (state) => trace.push(state));
  // Energy is conserved only between events; the stop state is a validity boundary, not physics.
  const accepted = run.stop === null ? trace : trace.slice(0, -1);
  for (const state of accepted) {
    maxDrift = Math.max(maxDrift, Math.abs(mechanicalEnergy(state, particle, system).total_J - start.total_J) / start.scale_J);
  }
  const reference = fixtureCase.reference;
  const commonT = Math.min(run.state.t_s, reference.t_s);
  let maxPath = 0;
  for (const row of reference.grid) {
    if (row[0] > commonT) break;
    const p = traceAt(trace, row[0]);
    maxPath = Math.max(maxPath, Math.hypot(p[0] - row[1], p[1] - row[2]));
  }
  const pEnd = traceAt(trace, commonT);
  const rEnd = referenceAt(reference.grid, commonT, fixtureCase);
  maxPath = Math.max(maxPath, Math.hypot(pEnd[0] - rEnd[0], pEnd[1] - rEnd[1]));
  const event = run.stop === null ? "none" : run.stop.reason;
  return {
    name: fixtureCase.name,
    event,
    referenceEvent: reference.event,
    eventTimeError: event !== "none" && event === reference.event ? Math.abs(run.stop.t_s - reference.eventTime_s) : null,
    invalid: run.invalid,
    maxPath,
    maxDrift,
    macroSteps: run.macroSteps,
    substepHistogram: run.substepHistogram,
    substepsTotal: trace.length - 1,
  };
}

function summarize(results) {
  const max = (key) => Math.max(...results.map((r) => r[key] ?? 0));
  const macro = results.reduce((sum, r) => sum + r.macroSteps, 0);
  const sub = results.reduce((sum, r) => sum + r.substepsTotal, 0);
  return {
    cases: results.length,
    eventMismatches: results.filter((r) => r.event !== r.referenceEvent).length,
    maxPathError_mm: max("maxPath") * 1e3,
    maxEnergyDrift_percent: max("maxDrift") * 100,
    maxEventTimeError_us: max("eventTimeError") * 1e6,
    meanSubstepMultiplier: sub / macro,
    events: results.reduce((acc, r) => ({ ...acc, [r.event]: (acc[r.event] ?? 0) + 1 }), {}),
  };
}

function assertGates(results, label) {
  for (const r of results) {
    assert.equal(r.invalid, null, `${r.name}: ${r.invalid}`);
    assert.equal(r.event, r.referenceEvent, `${r.name}: event ${r.event} vs reference ${r.referenceEvent}`);
    assert.ok(r.maxPath <= MAX_PATH_ERROR_M, `${r.name}: path error ${r.maxPath} m`);
    assert.ok(r.maxDrift <= MAX_ENERGY_DRIFT, `${r.name}: energy drift ${r.maxDrift}`);
  }
  const summary = summarize(results);
  assert.equal(summary.eventMismatches, 0, label);
  return summary;
}

test("7 representative trajectories match the RK4 reference within the approved gates", async (t) => {
  const fixture = await loadFixture("representative-rk4.json");
  assert.equal(fixture.cases.length, 7);
  const results = fixture.cases.map(evaluate);
  const summary = assertGates(results, "representative");
  for (const r of results) {
    t.diagnostic(`${r.name}: event=${r.event} path=${(r.maxPath * 1e3).toExponential(3)} mm drift=${(r.maxDrift * 100).toExponential(3)} % substeps=${JSON.stringify(r.substepHistogram)}`);
  }
  t.diagnostic(`summary ${JSON.stringify(summary)}`);
});

test("200 seeded Monte Carlo cases match the RK4 reference within the approved gates", async (t) => {
  const fixture = await loadFixture("monte-carlo-rk4.json");
  assert.equal(fixture.cases.length, 200);
  assert.equal(fixture.provenance.seed, 20260922);
  const results = fixture.cases.map(evaluate);
  const summary = assertGates(results, "monte carlo");
  assert.deepEqual(summary.events, { none: 165, "left-domain": 19, "entered-source-core": 16 });
  t.diagnostic(`summary ${JSON.stringify(summary)}`);
  t.diagnostic(`harness self-check ${JSON.stringify(fixture.provenance.harnessBoundedSelfCheck)}`);
});

test("N-01 fixed-step Verlet converges at second order on trajectories far from every core", async () => {
  const fixture = await loadFixture("monte-carlo-rk4.json");
  const far = fixture.cases.filter((c) => c.reference.event === "none" &&
    c.reference.grid.every((row) => c.sources.every((s) => Math.hypot(row[1] - s.x_m, row[2] - s.y_m) >= 3 * c.rCore_m)));
  assert.ok(far.length >= 6, `need 6 far trajectories, found ${far.length}`);
  const diagonal = Math.hypot(4, 3);
  for (const c of far.slice(0, 6)) {
    const system = systemOf(c);
    const particle = { q_C: c.qTest_C, mass_kg: c.mass_kg };
    const end = c.reference.grid[c.reference.grid.length - 1];
    const errorAt = (dt) => {
      let state = { x_m: c.r0_m[0], y_m: c.r0_m[1], vx_mps: c.v0_mps[0], vy_mps: c.v0_mps[1], t_s: 0 };
      const steps = Math.round(c.tEnd_s / dt);
      for (let i = 0; i < steps; i += 1) {
        const result = stepMacro(state, particle, system, dt);
        assert.equal(result.status, "advanced");
        assert.equal(result.substeps, 1, "far trajectories never need substeps");
        state = result.state;
      }
      return Math.hypot(state.x_m - end[1], state.y_m - end[2]);
    };
    const e1 = errorAt(MACRO_DT_S);
    const e2 = errorAt(MACRO_DT_S / 2);
    const e4 = errorAt(MACRO_DT_S / 4);
    assert.ok(e2 <= 0.35 * e1 || e1 < 1e-12, `${c.name}: e(dt/2)=${e2} e(dt)=${e1}`);
    assert.ok(e4 <= 0.35 * e2 || e2 < 1e-12, `${c.name}: e(dt/4)=${e4} e(dt/2)=${e2}`);
    assert.ok(e1 / diagonal <= 1e-3, `${c.name}: normalized end error ${e1 / diagonal}`);
  }
});

test("N-02 state is independent of how macro steps are batched into render frames", () => {
  const setup = ELECTROSTATIC_PRESETS.dipole;
  const finals = [];
  for (const perFrame of [32, 16, 8]) {
    // 30, 60 and 120 Hz schedules each consume 960 macro steps per simulated second.
    let runtime = initialRuntime(setup);
    for (let frame = 0; frame < 480 / perFrame; frame += 1) {
      for (let i = 0; i < perFrame; i += 1) runtime = stepRuntime(setup, runtime);
    }
    finals.push(runtime);
  }
  assert.deepEqual(finals[1], finals[0]);
  assert.deepEqual(finals[2], finals[0]);
});

test("bounded substeps are deterministic and exercise the 1 → 2 → 4 transitions", async () => {
  const fixture = await loadFixture("representative-rk4.json");
  const c = fixture.cases.find((item) => item.name === "envelope_limit_core_hit");
  const first = evaluate(c);
  const second = evaluate(c);
  assert.deepEqual(second, first);
  assert.ok(first.substepHistogram[1] > 0 && first.substepHistogram[2] > 0 && first.substepHistogram[4] > 0,
    `histogram ${JSON.stringify(first.substepHistogram)}`);
});

test("N-03 a core crossing stops at the first intersection with finite state", async () => {
  const fixture = await loadFixture("representative-rk4.json");
  for (const name of ["single_core_hit", "envelope_limit_core_hit", "dipole"]) {
    const c = fixture.cases.find((item) => item.name === name);
    const system = systemOf(c);
    const initial = { x_m: c.r0_m[0], y_m: c.r0_m[1], vx_mps: c.v0_mps[0], vy_mps: c.v0_mps[1], t_s: 0 };
    const trace = [initial];
    const run = integrateFor(initial, { q_C: c.qTest_C, mass_kg: c.mass_kg }, system, c.tEnd_s, (s) => trace.push(s));
    assert.equal(run.stop.reason, "entered-source-core");
    const nearest = Math.min(...system.sources.map((s) => Math.hypot(run.state.x_m - s.x_m, run.state.y_m - s.y_m)));
    assert.ok(Math.abs(nearest - c.rCore_m) <= 1e-12, `${name}: stop is on the core boundary (${nearest})`);
    for (const state of trace.slice(0, -1)) {
      const d = Math.min(...system.sources.map((s) => Math.hypot(state.x_m - s.x_m, state.y_m - s.y_m)));
      assert.ok(d > c.rCore_m, `${name}: no accepted state inside a core`);
    }
    for (const value of Object.values(run.state)) assert.ok(Number.isFinite(value));
    const again = stepMacro(run.state, { q_C: c.qTest_C, mass_kg: c.mass_kg }, system);
    // The rounded stop point sits on the boundary to ~1e-17 m, on either side. Stepping again must
    // never move the particle into the core: it is refused, or stops again where it is.
    assert.notEqual(again.status, "advanced", "stepping from the core boundary is never integrated");
    if (again.status === "invalid") assert.equal(again.reason, "inside-source-core");
    assert.ok(Math.hypot(again.state.x_m - run.state.x_m, again.state.y_m - run.state.y_m) <= 1e-15);
  }
});

test("N-04 leaving the domain stops on the rectangle with no out-of-domain sample", async () => {
  const fixture = await loadFixture("representative-rk4.json");
  for (const name of ["single_scatter", "like_pair", "zero_field_nearby"]) {
    const c = fixture.cases.find((item) => item.name === name);
    const trace = [];
    const run = integrateFor(
      { x_m: c.r0_m[0], y_m: c.r0_m[1], vx_mps: c.v0_mps[0], vy_mps: c.v0_mps[1], t_s: 0 },
      { q_C: c.qTest_C, mass_kg: c.mass_kg }, systemOf(c), c.tEnd_s, (s) => trace.push(s));
    assert.equal(run.stop.reason, "left-domain");
    const onEdge = [Math.abs(run.state.x_m) - 2, Math.abs(run.state.y_m) - 1.5].some((d) => Math.abs(d) <= 1e-12);
    assert.ok(onEdge, `${name}: stop lies on the boundary`);
    for (const s of trace) assert.ok(Math.abs(s.x_m) <= 2 + 1e-12 && Math.abs(s.y_m) <= 1.5 + 1e-12, `${name}: no wrap or bounce`);
  }
});

test("runtime step: a stopped particle stays stopped and an invalid start is typed, not thrown", () => {
  const setup = ELECTROSTATIC_PRESETS["single-positive"];
  const bad = { ...initialRuntime(setup), particle: { x_m: 0.05, y_m: 0, vx_mps: 0, vy_mps: 0, t_s: 0 } };
  const errored = stepRuntime(setup, bad);
  assert.equal(errored.error, "inside-source-core");
  assert.deepEqual(errored.particle, bad.particle);
  const stopped = { ...initialRuntime(setup), status: "stopped" };
  assert.equal(stepRuntime(setup, stopped), stopped);
});
